name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install gf
        run: go install github.com/pathcl/gf@latest

      - name: Try search
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gf search extension:go repo:pathcl/gf fmt.Println | grep fmt.Println | head -n1
